# Generated by Django 5.2 on 2025-04-24 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('level', models.CharField(choices=[('LEAD', 'Leadership'), ('SPEC', 'Specialist'), ('ENG', 'Engineering'), ('TECH', 'Technical'), ('OPER', 'Operational'), ('SUPP', 'Support')], default='OPER', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities for this position')),
                ('required_skills', models.TextField(blank=True, help_text='Skills required for this position')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='production.department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeanDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_type', models.CharField(choices=[('PROD', 'Production'), ('ASSY', 'Assembly'), ('QUAL', 'Quality Assurance'), ('SUPP', 'Supply Chain'), ('ENGR', 'Engineering'), ('MAINT', 'Maintenance'), ('PLAN', 'Planning'), ('OPER', 'Operations'), ('WRHSE', 'Warehouse'), ('LOGIS', 'Logistics'), ('MATLS', 'Materials Management'), ('RD', 'Research & Development'), ('TOOL', 'Tooling'), ('KAIZEN', 'Continuous Improvement'), ('VSM', 'Value Stream'), ('KANBAN', 'Kanban Management'), ('QCONT', 'Quality Control'), ('LEAN', 'Lean Office'), ('TPM', 'Total Productive Maintenance'), ('INNOV', 'Innovation')], max_length=10)),
                ('lean_principles', models.TextField(blank=True, help_text='Key lean principles implemented in this department')),
                ('kpis', models.TextField(blank=True, help_text='Key Performance Indicators tracked by this department')),
                ('improvement_initiatives', models.TextField(blank=True, help_text='Current improvement initiatives')),
                ('takt_time', models.FloatField(blank=True, help_text='Target takt time in minutes', null=True)),
                ('lead_time', models.FloatField(blank=True, help_text='Current lead time in days', null=True)),
                ('cycle_time', models.FloatField(blank=True, help_text='Average cycle time in minutes', null=True)),
                ('oee', models.FloatField(blank=True, help_text='Overall Equipment Effectiveness percentage', null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lean_details', to='production.department')),
            ],
        ),
        migrations.CreateModel(
            name='PositionDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary department for this position')),
                ('additional_requirements', models.TextField(blank=True, help_text='Additional requirements specific to this position in this department')),
                ('headcount', models.PositiveIntegerField(default=0, help_text='Number of people with this position in this department')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.position')),
            ],
            options={
                'verbose_name': 'Position-Department Relationship',
                'verbose_name_plural': 'Position-Department Relationships',
                'unique_together': {('position', 'department')},
            },
        ),
        migrations.AddField(
            model_name='position',
            name='departments',
            field=models.ManyToManyField(related_name='positions', through='production.PositionDepartment', to='production.department'),
        ),
    ]
