repos:
- repo: https://github.com/rochacbruno/djhtml
  rev: v3.0.3  # Use the latest stable version
  hooks:
    - id: djhtml

- repo: https://github.com/pre-commit/mirrors-pyright
  rev: v1.1.305  # Use the latest stable version
  hooks:
    - id: pyright

- repo: https://github.com/pytest-dev/pytest
  rev: 7.4.2  # Use the latest stable version
  hooks:
    - id: pytest

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0  # Use the latest stable version
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 23.9.1  # Use the latest stable version
  hooks:
    - id: black

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0  # Use the latest stable version
  hooks:
    - id: flake8

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.6.12
  hooks:
    - id: uv-lock

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.289
  hooks:
    - id: ruff

- repo: https://github.com/rtts/djhtml
  rev: 'main'  # replace with the latest tag on GitHub
  hooks:
    - id: djhtml
    - id: djcss
    - id: djjs

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.4
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format
